Repository microsoft/macos-cookbook, pull requests merged in 2019-01, with the labels that each got.

#176 Add `command_line_tools` resource
  .kitchen.yml
  README.md
  documentation/resource_command_line_tools.md
  libraries/command_line_tools.rb
  resources/command_line_tools.rb
  resources/xcode.rb
  spec/unit/resources/command_line_tools_spec.rb
  spec/unit/resources/xcode_spec.rb
  test/cookbooks/macos_test/metadata.rb
  test/cookbooks/macos_test/recipes/command_line_tools.rb
Labels: feature

#180 New Xcode Property: download_url
  .kitchen.yml
  CHANGELOG.md
  documentation/resource_xcode.md
  libraries/developer_account.rb
  libraries/xcode.rb
  libraries/xcversion.rb
  resources/xcode.rb
  spec/unit/libraries/xcode_spec.rb
  spec/unit/resources/xcode_spec.rb
  test/cookbooks/macos_test/recipes/xcode.rb
  test/cookbooks/macos_test/recipes/xcode_from_apple.rb
  test/cookbooks/macos_test/recipes/xcode_from_url.rb
Labels: feature

#179 Release/2.10.0
  .kitchen.yml
  CHANGELOG.md
  README.md
  attributes/default.rb
  documentation/resource_command_line_tools.md
  documentation/resource_xcode.md
  libraries/command_line_tools.rb
  libraries/developer_account.rb
  libraries/xcode.rb
  libraries/xcversion.rb
  metadata.rb
  resources/command_line_tools.rb
  resources/xcode.rb
  spec/spec_helper.rb
  spec/unit/libraries/macos_user_spec.rb
  spec/unit/libraries/xcode_spec.rb
  spec/unit/libraries/xcversion_spec.rb
  spec/unit/resources/command_line_tools_spec.rb
  spec/unit/resources/xcode_spec.rb
  test/cookbooks/macos_test/metadata.rb
  test/cookbooks/macos_test/recipes/command_line_tools.rb
  test/cookbooks/macos_test/recipes/xcode.rb
  test/cookbooks/macos_test/recipes/xcode_from_apple.rb
  test/cookbooks/macos_test/recipes/xcode_from_url.rb
  test/integration/default/controls/xcode_test.rb
Labels: release

#182 Hotfix/2.10.1
  CHANGELOG.md
  libraries/machine_name.rb
  metadata.rb
  resources/machine_name.rb
  test/cookbooks/macos_test/recipes/machine_name.rb
Labels: bug
